# Generated by Django 3.1.7 on 2021-10-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gebblesalert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningsrelatednotifications',
            old_name='e1t1objectoflearning',
            new_name='e1t1object',
        ),
    ]
