# Generated by Django 3.1.7 on 2021-11-08 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0008_auto_20211107_0820'),
        ('gebblesalert', '0002_auto_20211011_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsE1T1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('notification_context', models.IntegerField(choices=[(1, 'e1t1'), (2, 'learnings'), (3, 'private_messages')])),
                ('notification_type', models.IntegerField(choices=[(1, 'creation'), (2, 'like'), (3, 'comment')])),
                ('is_seen', models.BooleanField(default=False)),
                ('chatobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notichatobject', to='sharing.sharingmessage')),
                ('e1t1object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notie1t1object', to='sharing.sharing')),
                ('learningobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notilearningobject', to='sharing.learnings')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notitouserobject', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifromuserobject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
