# Generated by Django 3.1.7 on 2021-11-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_auto_20211107_0820'),
        ('gebblesalert', '0003_notificationse1t1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsrelatednotifications',
            name='e1t1object',
        ),
        migrations.RemoveField(
            model_name='learningsrelatednotifications',
            name='learningobject',
        ),
        migrations.RemoveField(
            model_name='learningsrelatednotifications',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='learningsrelatednotifications',
            name='sender',
        ),
        migrations.AlterField(
            model_name='notificationse1t1',
            name='chatobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notichatobject', to='sharing.sharingmessage'),
        ),
        migrations.AlterField(
            model_name='notificationse1t1',
            name='learningobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notilearningobject', to='sharing.learnings'),
        ),
        migrations.DeleteModel(
            name='E1T1Notification',
        ),
        migrations.DeleteModel(
            name='LearningsRelatedNotifications',
        ),
    ]
