# Generated by Django 3.1.7 on 2021-11-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gebblesalert', '0004_auto_20211108_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationse1t1',
            name='receiver2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notitouser2object', to='user.user'),
            preserve_default=False,
        ),
    ]
