# Generated by Django 3.1.7 on 2021-09-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_auto_20210907_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='teacher',
        ),
        migrations.AddField(
            model_name='alert',
            name='areceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertreceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertsender', to=settings.AUTH_USER_MODEL),
        ),
    ]
