# Generated by Django 3.1.7 on 2021-08-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdata',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
