# Generated by Django 3.1.7 on 2021-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdata',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='ig',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
