# Generated by Django 3.1.7 on 2021-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210818_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='journeytag',
            field=models.CharField(choices=[('ev', 'event'), ('ca', 'notagjustcasual'), ('wo', 'workshop'), ('ju', 'judging'), ('mu', 'music')], default='ca', max_length=2),
        ),
    ]
