# Generated by Django 3.1.7 on 2021-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20210330_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='ishighlight',
            field=models.BooleanField(default=False),
        ),
    ]
