# Generated by Django 3.1.7 on 2021-05-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='isprivate',
            field=models.BooleanField(default=False),
        ),
    ]
