# Generated by Django 3.1.7 on 2021-05-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_journey_isprivate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlights',
        ),
    ]
