# Generated by Django 3.1.7 on 2021-05-31 11:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_delete_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdata',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'HIPHOP'), (2, 'HOUSE'), (3, 'POPPING'), (4, 'LOCKING'), (5, 'BREAKING'), (6, 'EXPERIMENTAL'), (7, 'OTHER'), (8, 'STILL EXPLORING')], default='', max_length=15),
        ),
    ]
