# Generated by Django 3.1.7 on 2021-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_artistdata_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdata',
            name='vid1',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='vid2',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='vid3',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='vid4',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
