# Generated by Django 3.1.7 on 2021-06-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20210602_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistdata',
            name='styles',
        ),
    ]
