# Generated by Django 3.1.7 on 2021-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20210602_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='test',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
