# Generated by Django 3.1.7 on 2021-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20210602_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='jophoto',
            new_name='jophoto1',
        ),
        migrations.AddField(
            model_name='journey',
            name='jophoto2',
            field=models.ImageField(default='', upload_to='events_attended/'),
        ),
        migrations.AddField(
            model_name='journey',
            name='jophoto3',
            field=models.ImageField(default='', upload_to='events_attended/'),
        ),
        migrations.AddField(
            model_name='journey',
            name='jophoto4',
            field=models.ImageField(default='', upload_to='events_attended/'),
        ),
        migrations.AddField(
            model_name='journey',
            name='jophoto5',
            field=models.ImageField(default='', upload_to='events_attended/'),
        ),
    ]
