# Generated by Django 3.1.7 on 2021-06-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20210626_1257'),
        ('artist', '0009_remove_artistdata_styles'),
    ]

    operations = [
    ]
