# Generated by Django 3.1.7 on 2021-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20210702_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
