# Generated by Django 3.1.7 on 2021-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_auto_20210702_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
