# Generated by Django 3.1.7 on 2021-07-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0015_auto_20210702_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='artist',
            name='thumb',
            field=models.ImageField(editable=False, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
