# Generated by Django 3.1.7 on 2021-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_auto_20210702_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='jocontent',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='journey',
            name='jodate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='jolink',
            field=models.URLField(default='', max_length=255),
        ),
    ]
