# Generated by Django 3.1.7 on 2021-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_auto_20210708_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='jophoto1',
            field=models.ImageField(blank=True, default='', upload_to='events_attended/'),
        ),
    ]
