# Generated by Django 3.1.7 on 2021-02-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0002_auto_20210226_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='onlineclass.workshop'),
        ),
    ]
