# Generated by Django 3.1.7 on 2021-06-05 15:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='covers/'),
        ),
    ]
