# Generated by Django 3.1.7 on 2021-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='s_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
