# Generated by Django 3.1.7 on 2021-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20210226_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
