# Generated by Django 3.1.7 on 2021-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_learnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnings',
            name='videouploaded',
            field=models.BooleanField(default=False),
        ),
    ]
