# Generated by Django 3.1.7 on 2021-10-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0004_learnings_videouploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesForLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('LO', 'love'), ('FI', 'fire'), ('DE', 'deep')], default='LO', max_length=2)),
                ('learningid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lflid', to='sharing.learnings')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lfluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
