# Generated by Django 3.1.7 on 2021-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_auto_20210308_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingmessage',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
