# Generated by Django 3.1.7 on 2021-03-26 06:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_sharingmessage_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='s_student_country',
            field=django_countries.fields.CountryField(default='NP', max_length=2),
            preserve_default=False,
        ),
    ]
