# Generated by Django 3.1.7 on 2021-10-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_auto_20211008_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsforlearning',
            old_name='learningid',
            new_name='learningidobj',
        ),
        migrations.RenameField(
            model_name='commentsforsharing',
            old_name='shareid',
            new_name='shareidobj',
        ),
        migrations.RenameField(
            model_name='likesforlearning',
            old_name='learningid',
            new_name='learningidobj',
        ),
        migrations.RenameField(
            model_name='loveforsharing',
            old_name='shareid',
            new_name='shareidobj',
        ),
    ]
