# Generated by Django 3.1.7 on 2021-03-26 06:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_sharing_s_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='s_student_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='s_teacher_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
    ]
