# Generated by Django 3.1.7 on 2021-04-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_auto_20210326_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='c_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='c_comment',
            field=models.TextField(default=''),
        ),
    ]
