# Generated by Django 3.1.7 on 2021-11-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_auto_20211008_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='s_video_dance',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='s_video_talk',
        ),
        migrations.AddField(
            model_name='sharing',
            name='s_learnings',
            field=models.TextField(default=''),
        ),
    ]
