# Generated by Django 3.1.7 on 2021-06-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_auto_20210406_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='s_teacher_video',
            field=models.CharField(default='', max_length=255),
        ),
    ]
