# Generated by Django 3.1.7 on 2021-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0009_sharing_s_teacher_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='s_appreciation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='s_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='s_teacher_video',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
