# Generated by Django 3.1.7 on 2021-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0010_auto_20210614_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='s_learnings',
            field=models.TextField(default=''),
        ),
    ]
